### ISSUE TITLE
Todo List -- 接受意见，不一定采纳，视需而定

### ISSUE THREAD

**Issue by wewall** [wewall/ss-panel-v3-mod_Uim#4]
- telegram 一键注册登陆。

- telegram 群组@人禁用对应账户

- 修改邮箱退订，确认即可退订，不用进入 /user/edit （涉及数据库改动，分开提交）

**Comment by wewall** [comment]
- 跨省登陆拦截（新增表，选择性）

- 二开SSR，多客户端检测改为MAC地址+公网IP，防止局域网内多个用户同个账号登陆，其他客户端实现思路，类同，无交期。

**Comment by NimaQu** [comment]
不愧是 RBQ

**Comment by wewall** [comment]
@NimaQu  绒布球你来了啊

**Comment by wewall** [comment]
- 只有付费会员才能开启工单，发起在线聊天

**Comment by wewall** [comment]
- 优化签到：改为签到 & /checkin

**Comment by wewall** [comment]
- 一键设置免流混淆
